FROM python
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN useradd web && mkdir /home/web
COPY service.py /home/web/service.py
COPY elf_dict.py /home/web/elf_dict.py
RUN chown -R web /home/web
COPY dev_server.py /root/dev_server.py
COPY runner.sh /root/runner.sh
WORKDIR /root
ENTRYPOINT [ "/bin/bash", "/root/runner.sh" ]